# Generated by Django 5.0.6 on 2026-06-20 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ward_type', models.CharField(choices=[('GENERAL', 'General'), ('ICU', 'ICU'), ('NICU', 'NICU'), ('PRIVATE', 'Private'), ('SEMI_PRIVATE', 'Semi Private'), ('HDU', 'HDU')], max_length=20)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('capacity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ward',
                'verbose_name_plural': 'wards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=20)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='wards.ward')),
            ],
            options={
                'verbose_name': 'bed',
                'verbose_name_plural': 'beds',
                'ordering': ['ward', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wards.bed')),
            ],
            options={
                'verbose_name': 'admission',
                'verbose_name_plural': 'admissions',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('ward', 'bed_number'), name='unique_bed_per_ward'),
        ),
    ]
