# Generated by Django 5.0.6 on 2026-06-20 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('emr', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('normal_range', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'lab test',
                'verbose_name_plural': 'lab tests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=20)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'Stat')], default='ROUTINE', max_length=20)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emr.medicalrecord')),
            ],
            options={
                'verbose_name': 'lab order',
                'verbose_name_plural': 'lab orders',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True)),
                ('flag', models.CharField(blank=True, max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.laborder')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratory.labtest')),
            ],
            options={
                'verbose_name': 'lab order item',
                'verbose_name_plural': 'lab order items',
                'ordering': ['order', 'test'],
            },
        ),
        migrations.AddField(
            model_name='laborder',
            name='tests',
            field=models.ManyToManyField(through='laboratory.LabOrderItem', to='laboratory.labtest'),
        ),
        migrations.AddConstraint(
            model_name='laborderitem',
            constraint=models.UniqueConstraint(fields=('order', 'test'), name='unique_test_per_lab_order'),
        ),
    ]
